### ISSUE TITLE
Error while compiling the project

### ISSUE THREAD

**Issue by nelth-fr** [wcisco17/gatsby-typescript-shards-starter#2]
`success building schema - 0.179s
success createPages - 0.001s
success createPagesStatefully - 0.045s
success onPreExtractQueries - 0.001s
success update schema - 0.019s
success extract queries from components - 0.215s
success write out requires - 0.017s
success write out redirect data - 0.002s
[gatsby-plugin-generate-types] Wrote schema
[gatsby-plugin-generate-types] Starting Apollo Codegen Watcher
⠋ onPostBootstrap
⠋ Build manifest and related icons
/Users/nelth/.nvm/versions/node/v12.14.0/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: spawn apollo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn apollo',
  path: 'apollo',
  spawnargs: [
    'client:codegen',
    '--target=typescript',
    '--localSchemaFile=schema.json',
    '--tagName=graphql',
    '--watch',
    '_types'
  ]
}`

Hi, I'm really excited about this Gatsby template, there is an issue while cloning/creating the project, Node throw this weird error...

I've been trying to go back on the history of the project at key moments where error could happen but I have no idea or even clue to solve this.

It's a shame because I'm a back-end guy and this UI seems really decent =)
Well, I'll be watching if there is any update, have a good night !

**Comment by wcisco17** [comment]
Hey fixing the error rn - thanks for the feedback!

**Comment by wcisco17** [comment]
Hey I think it should work now - please let me know if you still get the error @nelth-fr

**Comment by nelth-fr** [comment]
Hum, still having the same issue. Maybe it's something related to version management... ?

$ node --version
`v12.14.0`

$ gatsby --version 
`Gatsby CLI version: 2.11.5
Gatsby version: 2.20.12
  Note: this is the Gatsby version for the site at: /Users/nelth/WORKSPACE/gatsby-typescript-shards-starter`

**Comment by wcisco17** [comment]
Can you try with yarn?

**Comment by SEsseltine** [comment]
> Can you try with yarn?

Hey, I am also excited about this template. I tried this evening using both yarn and npm with no luck.

**Comment by 0xinsanity** [comment]
Getting same issue here, please keep me updated if someone has fixed this!

**Comment by 0xinsanity** [comment]
Actually I seemed to have fixed it. If you change the start script to be "yarn run develop" and run "yarn start", that seemed to work for me.
